name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build-win_latest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          New-Item -ItemType directory -Path build
          cmake -S . -B build
          cmake --build build/ --config Debug -j
          cmake --build build/ --config RelWithDebInfo -j

      - name: Upload build files
        uses: actions/upload-artifact@v4.3.1
        with:
          name: artifact
          path: |
            ./build/Debug
            ./build/RelWithDebInfo

  build-linux_ubuntu-2004:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.0.0

        - name: Install Packages
          run: |
            sudo apt update
            sudo apt install -y cmake libc++1-12 libc++abi-12-dev libc++-12-dev libc++abi1-12 clang-12

        - name: Build
          run: git clone --recursive https://github.com/kubo/funchook.git -b v1.1.3 deps/funchook && mkdir build && cd build && cmake .. && make -j4

        - name: Upload build files
          uses: actions/upload-artifact@v4.3.1
          with:
            name: artifact-linux
            path: |
              ./build/

  build-linux_ubuntu-1804:
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.0.0

        - name: Install Packages
          run: |
            sudo apt update
            sudo apt install -y cmake libc++1-12 libc++abi-12-dev libc++-12-dev libc++abi1-12 clang-12

        - name: Build
          run: git clone --recursive https://github.com/kubo/funchook.git -b v1.1.3 deps/funchook && mkdir build && cd build && cmake .. && make -j4

        - name: Upload build files
          uses: actions/upload-artifact@v4.3.1
          with:
            name: artifact-linux
            path: |
              ./build/